### ISSUE TITLE
can i use yolov2 custom .pb file for this? IF yes can you tell me how?

### ISSUE THREAD

**Issue by luthfi07** [mohamadassaf96/TFLiteAndroid#1]

**Comment by mohamadassaf96** [comment]
Hi Lutfi, please refer to the second point in "Notes" section. Depending on whether you are using a detection or a classification model, inherit from the corresponding class. Now there are characteristics that you have to find out in your model, for example dimensions of input image, number of bytes per channel … You can refer to tensorboard to view your model and inspect it. Do exactly as I did inheriting "InceptionV3Float" from "ImageClassifier" or "SSDdetectorQuant" from "ImageDetector"
